name: Terraform

on:
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        id: init
        run: terraform init -input=false
        working-directory: ./terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -var="project_id=${{ secrets.GCP_PROJECT }}" -var="credentials=${{ secrets.GCP_SA_KEY }}" -var="zone=${{ secrets.GKE_ZONE }}"
        working-directory: ./terraform

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -input=false -var="project_id=${{ secrets.GCP_PROJECT }}" -var="credentials=${{ secrets.GCP_SA_KEY }}" -var="zone=${{ secrets.GKE_ZONE }}"
        working-directory: ./terraform