name: Terraform CI/CD

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.5.0"

    - name: Configure GCP Credentials
      run: |
        mkdir -p $HOME/.config/gcloud
        echo '${{ secrets.GCP_SA_KEY }}' > $HOME/.config/gcloud/credentials.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/.config/gcloud/credentials.json" >> $GITHUB_ENV

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform
      env:
        GOOGLE_APPLICATION_CREDENTIALS: $HOME/.config/gcloud/credentials.json

    - name: Terraform Plan
      run: terraform plan -var="project_id=${{ secrets.GCP_PROJECT }}" -var="zone=${{ secrets.GKE_ZONE }}"
      working-directory: ./terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve -var="project_id=${{ secrets.GCP_PROJECT }}" -var="zone=${{ secrets.GKE_ZONE }}"
      working-directory: ./terraform